services:
    # AUTH
    auth_db:
        build: database
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        volumes:
            - auth_db_volume:/var/lib/postgresql/data
        networks:
            - app-network

    auth:
        depends_on:
            - auth_db
        command:
            [
                "/bin/bash",
                "-c",
                "python3 /backend/app/migrate.py && uvicorn app.main:app --reload --host 0.0.0.0 --port 4000"
            ]
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - JWT_SECRET=${JWT_SECRET}
        build: auth
        restart: always
        ports:
            - "4001:4000" # host:container
        volumes:
            - ./auth/app:/backend/app
        networks:
            - app-network

    # PROJECT
    project_db:
        build: database
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        volumes:
            - project_db_volume:/var/lib/postgresql/data
        networks:
            - app-network

    project:
        depends_on:
            - project_db
        command:
            [
                "/bin/bash",
                "-c",
                "python3 /backend/app/migrate.py && uvicorn app.main:app --reload --host 0.0.0.0 --port 4000"
            ]
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        build: project
        restart: always
        ports:
            - "4002:4000" # host:container                    
        volumes:
            - ./project/app:/backend/app
        networks:
            - app-network

    # EXPERT
    expert_db:
        build: database
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
        volumes:
            - expert_db_volume:/var/lib/postgresql/data
        networks:
            - app-network

    expert:
        platform: linux/amd64
        depends_on:
            - expert_db
        command:
            [
                "/bin/bash",
                "-c",
                "python3 /backend/app/migrate.py && uvicorn app.main:app --reload --host 0.0.0.0 --port 4000"
            ]
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        build: expert
        restart: always
        ports:
            - "4003:4000" # host:container            
        volumes:
            - ./expert/app:/backend/app
        networks:
            - app-network

    # FRONTEND
    frontend:
        build:
            dockerfile: Dockerfile
            context: ./web
            args:
                AUTH_API_HOST: ${AUTH_API_HOST}
                PROJECT_API_HOST: ${PROJECT_API_HOST}
                EXPERT_API_HOST: ${EXPERT_API_HOST}
        command: [ "/bin/bash", "-c", "npm run start" ]
        restart: always
        ports:
            - "3000:3000" # host:container
        environment:
            - JWT_SECRET=${JWT_SECRET}
        networks:
            - app-network 

volumes:
    auth_db_volume:
    project_db_volume:
    expert_db_volume:

networks:
    app-network:
        driver: bridge